name: Build FamilyDesk - iOS

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  RUST_VERSION: "1.75"
  VERSION: "1.4.2"
  RS_PUB_KEY: "iQX+6aUbS40CL9jJElm4jSMs8aKzePqMsFH1HACDI5E="
  RENDEZVOUS_SERVER: "nas.haydenstudio.hk"
  API_SERVER: "http://nas.haydenstudio.hk:21114"
  FLUTTER_VERSION: "3.13.9"

jobs:
  build-ios:
    name: "Build FamilyDesk for iOS"
    runs-on: macos-13
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true

      - name: Install Rust iOS targets
        run: |
          rustup target add aarch64-apple-ios
          rustup target add x86_64-apple-ios

      - name: Install cargo-lipo
        run: |
          cargo install cargo-lipo

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0'

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Install Flutter dependencies
        working-directory: flutter
        run: |
          flutter pub get
          cd ios
          pod install

      - name: Build iOS app (无签名)
        working-directory: flutter
        run: |
          flutter build ios --release --no-codesign

      - name: Create IPA (Ad-hoc)
        working-directory: flutter/ios
        run: |
          # 创建 Payload 目录结构
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/

          # 打包为 IPA
          zip -r FamilyDesk.ipa Payload

          echo "IPA created (未签名，仅用于开发测试)"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: familydesk-ios-${{ env.VERSION }}-unsigned
          path: flutter/ios/FamilyDesk.ipa

      - name: Upload Runner.app
        uses: actions/upload-artifact@v4
        with:
          name: familydesk-ios-app-${{ env.VERSION }}
          path: flutter/build/ios/iphoneos/Runner.app
