name: Build FamilyDesk - Windows

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  RUST_VERSION: "1.75"
  VERSION: "1.4.2"
  RS_PUB_KEY: "iQX+6aUbS40CL9jJElm4jSMs8aKzePqMsFH1HACDI5E="
  RENDEZVOUS_SERVER: "nas.haydenstudio.hk"
  API_SERVER: "http://nas.haydenstudio.hk:21114"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"

jobs:
  build-windows:
    name: "Build FamilyDesk for Windows"
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          target: x86_64-pc-windows-msvc
          profile: minimal
          override: true

      - name: Install LLVM and Clang
        run: |
          choco install llvm -y
          echo "LIBCLANG_PATH=C:\Program Files\LLVM\bin" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout ${{ env.VCPKG_COMMIT_ID }}
          .\bootstrap-vcpkg.bat
          echo "VCPKG_ROOT=$PWD" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Install vcpkg dependencies
        run: |
          $env:VCPKG_ROOT = "$(Get-Location)\vcpkg"
          cd vcpkg
          .\vcpkg.exe install --triplet x64-windows-static

      - name: Build FamilyDesk (Core Features)
        run: |
          cargo build --features family_desk --release

      - name: Verify build
        run: |
          dir target\release\rustdesk.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: familydesk-windows-${{ env.VERSION }}
          path: target/release/rustdesk.exe
