name: Build FamilyDesk - Android

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - master
  pull_request:

env:
  RUST_VERSION: "1.75"
  VERSION: "1.4.2"
  RS_PUB_KEY: "iQX+6aUbS40CL9jJElm4jSMs8aKzePqMsFH1HACDI5E="
  RENDEZVOUS_SERVER: "nas.haydenstudio.hk"
  API_SERVER: "http://nas.haydenstudio.hk:21114"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  NDK_VERSION: "r26b"
  FLUTTER_VERSION: "3.13.9"
  PKG_CONFIG_PATH: /usr/lib/x86_64-linux-gnu/pkgconfig:/usr/share/pkgconfig:/usr/lib/pkgconfig

jobs:
  build-android:
    name: "Build FamilyDesk for Android"
    runs-on: ubuntu-20.04
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          channel: 'stable'

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          profile: minimal
          override: true

      - name: Install Rust Android targets
        run: |
          rustup target add aarch64-linux-android
          rustup target add armv7-linux-androideabi
          rustup target add x86_64-linux-android

      - name: Install cargo-ndk
        run: |
          cargo install cargo-ndk

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: ${{ env.NDK_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y libglib2.0-dev pkg-config \
            llvm-dev libclang-dev clang nasm yasm

      - name: Setup vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg
          cd vcpkg
          git checkout ${{ env.VCPKG_COMMIT_ID }}
          ./bootstrap-vcpkg.sh
          echo "VCPKG_ROOT=$PWD" >> $GITHUB_ENV

      - name: Build Flutter Android App
        working-directory: flutter
        run: |
          flutter pub get
          flutter build apk --release --target-platform android-arm64

      - name: Verify build
        run: |
          ls -lh flutter/build/app/outputs/flutter-apk/app-release.apk

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: familydesk-android-${{ env.VERSION }}
          path: flutter/build/app/outputs/flutter-apk/app-release.apk

      - name: Build Android App Bundle (AAB)
        working-directory: flutter
        run: |
          flutter build appbundle --release

      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: familydesk-android-bundle-${{ env.VERSION }}
          path: flutter/build/app/outputs/bundle/release/app-release.aab
